namespace Service_Program.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedSensorsToDefaultDevs : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.PresetDevs", "Sensor1_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor10_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor11_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor12_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor13_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor14_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor15_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor16_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor17_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor18_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor19_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor2_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor20_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor21_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor22_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor23_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor24_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor25_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor26_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor27_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor28_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor29_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor3_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor30_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor31_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor32_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor33_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor34_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor35_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor36_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor37_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor38_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor39_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor4_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor40_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor5_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor6_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor7_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor8_Id", c => c.Int());
            AddColumn("dbo.PresetDevs", "Sensor9_Id", c => c.Int());
            CreateIndex("dbo.PresetDevs", "Sensor1_Id");
            CreateIndex("dbo.PresetDevs", "Sensor10_Id");
            CreateIndex("dbo.PresetDevs", "Sensor11_Id");
            CreateIndex("dbo.PresetDevs", "Sensor12_Id");
            CreateIndex("dbo.PresetDevs", "Sensor13_Id");
            CreateIndex("dbo.PresetDevs", "Sensor14_Id");
            CreateIndex("dbo.PresetDevs", "Sensor15_Id");
            CreateIndex("dbo.PresetDevs", "Sensor16_Id");
            CreateIndex("dbo.PresetDevs", "Sensor17_Id");
            CreateIndex("dbo.PresetDevs", "Sensor18_Id");
            CreateIndex("dbo.PresetDevs", "Sensor19_Id");
            CreateIndex("dbo.PresetDevs", "Sensor2_Id");
            CreateIndex("dbo.PresetDevs", "Sensor20_Id");
            CreateIndex("dbo.PresetDevs", "Sensor21_Id");
            CreateIndex("dbo.PresetDevs", "Sensor22_Id");
            CreateIndex("dbo.PresetDevs", "Sensor23_Id");
            CreateIndex("dbo.PresetDevs", "Sensor24_Id");
            CreateIndex("dbo.PresetDevs", "Sensor25_Id");
            CreateIndex("dbo.PresetDevs", "Sensor26_Id");
            CreateIndex("dbo.PresetDevs", "Sensor27_Id");
            CreateIndex("dbo.PresetDevs", "Sensor28_Id");
            CreateIndex("dbo.PresetDevs", "Sensor29_Id");
            CreateIndex("dbo.PresetDevs", "Sensor3_Id");
            CreateIndex("dbo.PresetDevs", "Sensor30_Id");
            CreateIndex("dbo.PresetDevs", "Sensor31_Id");
            CreateIndex("dbo.PresetDevs", "Sensor32_Id");
            CreateIndex("dbo.PresetDevs", "Sensor33_Id");
            CreateIndex("dbo.PresetDevs", "Sensor34_Id");
            CreateIndex("dbo.PresetDevs", "Sensor35_Id");
            CreateIndex("dbo.PresetDevs", "Sensor36_Id");
            CreateIndex("dbo.PresetDevs", "Sensor37_Id");
            CreateIndex("dbo.PresetDevs", "Sensor38_Id");
            CreateIndex("dbo.PresetDevs", "Sensor39_Id");
            CreateIndex("dbo.PresetDevs", "Sensor4_Id");
            CreateIndex("dbo.PresetDevs", "Sensor40_Id");
            CreateIndex("dbo.PresetDevs", "Sensor5_Id");
            CreateIndex("dbo.PresetDevs", "Sensor6_Id");
            CreateIndex("dbo.PresetDevs", "Sensor7_Id");
            CreateIndex("dbo.PresetDevs", "Sensor8_Id");
            CreateIndex("dbo.PresetDevs", "Sensor9_Id");
            AddForeignKey("dbo.PresetDevs", "Sensor1_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor10_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor11_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor12_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor13_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor14_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor15_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor16_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor17_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor18_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor19_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor2_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor20_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor21_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor22_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor23_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor24_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor25_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor26_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor27_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor28_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor29_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor3_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor30_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor31_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor32_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor33_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor34_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor35_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor36_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor37_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor38_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor39_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor4_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor40_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor5_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor6_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor7_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor8_Id", "dbo.Sensors", "Id");
            AddForeignKey("dbo.PresetDevs", "Sensor9_Id", "dbo.Sensors", "Id");
            DropColumn("dbo.PresetDevs", "Reference");
            DropColumn("dbo.PresetDevs", "Price");
        }
        
        public override void Down()
        {
            AddColumn("dbo.PresetDevs", "Price", c => c.String(unicode: false));
            AddColumn("dbo.PresetDevs", "Reference", c => c.String(unicode: false));
            DropForeignKey("dbo.PresetDevs", "Sensor9_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor8_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor7_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor6_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor5_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor40_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor4_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor39_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor38_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor37_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor36_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor35_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor34_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor33_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor32_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor31_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor30_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor3_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor29_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor28_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor27_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor26_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor25_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor24_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor23_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor22_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor21_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor20_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor2_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor19_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor18_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor17_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor16_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor15_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor14_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor13_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor12_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor11_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor10_Id", "dbo.Sensors");
            DropForeignKey("dbo.PresetDevs", "Sensor1_Id", "dbo.Sensors");
            DropIndex("dbo.PresetDevs", new[] { "Sensor9_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor8_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor7_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor6_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor5_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor40_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor4_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor39_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor38_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor37_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor36_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor35_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor34_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor33_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor32_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor31_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor30_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor3_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor29_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor28_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor27_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor26_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor25_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor24_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor23_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor22_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor21_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor20_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor2_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor19_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor18_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor17_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor16_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor15_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor14_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor13_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor12_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor11_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor10_Id" });
            DropIndex("dbo.PresetDevs", new[] { "Sensor1_Id" });
            DropColumn("dbo.PresetDevs", "Sensor9_Id");
            DropColumn("dbo.PresetDevs", "Sensor8_Id");
            DropColumn("dbo.PresetDevs", "Sensor7_Id");
            DropColumn("dbo.PresetDevs", "Sensor6_Id");
            DropColumn("dbo.PresetDevs", "Sensor5_Id");
            DropColumn("dbo.PresetDevs", "Sensor40_Id");
            DropColumn("dbo.PresetDevs", "Sensor4_Id");
            DropColumn("dbo.PresetDevs", "Sensor39_Id");
            DropColumn("dbo.PresetDevs", "Sensor38_Id");
            DropColumn("dbo.PresetDevs", "Sensor37_Id");
            DropColumn("dbo.PresetDevs", "Sensor36_Id");
            DropColumn("dbo.PresetDevs", "Sensor35_Id");
            DropColumn("dbo.PresetDevs", "Sensor34_Id");
            DropColumn("dbo.PresetDevs", "Sensor33_Id");
            DropColumn("dbo.PresetDevs", "Sensor32_Id");
            DropColumn("dbo.PresetDevs", "Sensor31_Id");
            DropColumn("dbo.PresetDevs", "Sensor30_Id");
            DropColumn("dbo.PresetDevs", "Sensor3_Id");
            DropColumn("dbo.PresetDevs", "Sensor29_Id");
            DropColumn("dbo.PresetDevs", "Sensor28_Id");
            DropColumn("dbo.PresetDevs", "Sensor27_Id");
            DropColumn("dbo.PresetDevs", "Sensor26_Id");
            DropColumn("dbo.PresetDevs", "Sensor25_Id");
            DropColumn("dbo.PresetDevs", "Sensor24_Id");
            DropColumn("dbo.PresetDevs", "Sensor23_Id");
            DropColumn("dbo.PresetDevs", "Sensor22_Id");
            DropColumn("dbo.PresetDevs", "Sensor21_Id");
            DropColumn("dbo.PresetDevs", "Sensor20_Id");
            DropColumn("dbo.PresetDevs", "Sensor2_Id");
            DropColumn("dbo.PresetDevs", "Sensor19_Id");
            DropColumn("dbo.PresetDevs", "Sensor18_Id");
            DropColumn("dbo.PresetDevs", "Sensor17_Id");
            DropColumn("dbo.PresetDevs", "Sensor16_Id");
            DropColumn("dbo.PresetDevs", "Sensor15_Id");
            DropColumn("dbo.PresetDevs", "Sensor14_Id");
            DropColumn("dbo.PresetDevs", "Sensor13_Id");
            DropColumn("dbo.PresetDevs", "Sensor12_Id");
            DropColumn("dbo.PresetDevs", "Sensor11_Id");
            DropColumn("dbo.PresetDevs", "Sensor10_Id");
            DropColumn("dbo.PresetDevs", "Sensor1_Id");
        }
    }
}
